### ISSUE TITLE
Google assistant key on Pixelbook

### ISSUE THREAD

**Issue by denneyg** [WeirdTreeThing/cros-keyboard-map#11]
Is there any way to remap the Google Assistant key on the Pixelbook (Eve)?

**Comment by WeirdTreeThing** [comment]
What keycode do you get in evtest when you press it?

**Comment by denneyg** [comment]
It generates type 4 )EV_MSC), code 4 (MSC_SCAN), value d8

Gary

**Comment by WeirdTreeThing** [comment]
Create the file `/etc/udev/hwdb.d/61-eve-keyboard.hwdb` and add the following:

```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnGoogle:pnEve:pvr*
 KEYBOARD_KEY_d8=leftmeta
```

Then reboot

I dont think keyd is able to map this special key

**Comment by sporeking** [comment]
I have run the script to fix my google assistant key. However, neither before and after running the script make the assistant key available. In evtest I get nothing when I press the Google assistant key, but any other key is available. How can I make the assistant key available?

**Comment by WeirdTreeThing** [comment]
I just added support for this in the script. Pull my changes and see if it works now.

**Comment by sporeking** [comment]
Thanks for your help. But it seems that the situation has not improved.  I have tried to modify 61-eve-keyboard.hwdb myself, but it didn't achieve any results. I am now very curious about which link is wrong. 
My pixelbook go is second-hand, and it was installed with manjaro when it came to me, so I don't know how the original owner flashed the UEFI firmware. I reinstalled arch linux myself, but the audio, keyboard mapping and other problems were not successfully fixed. Is there something wrong with my own installation? I plan to reinstall it according to Chrultrabook Docs when I have time in the future, but now I decided to make do with it, anyway, the Google Assistant key is not convenient. Anyway, thanks for your help.

**Comment by WeirdTreeThing** [comment]
Try running evtest on it with the hwdb config and see which key it reports as.

**Comment by sporeking** [comment]
When I prees the assistant key, nothing happened in evtest, as if i never press any key. I even suspect this key is broken. But all other keys were normal, as evtest can tell me which key i pressed.

**Comment by uiYzzi** [comment]
> When I prees the assistant key, nothing happened in evtest, as if i never press any key. I even suspect this key is broken. But all other keys were normal, as evtest can tell me which key i pressed.

me too

**Comment by ChocolateLoverRaj** [comment]
> I even suspect this key is broken.

- Did it work on ChromeOS?
- If you press it does your Pixelbook wake up from suspend?

**Comment by livexia** [comment]
After install this utility, pixelbook go's keyboard is remaped, but only the google assistant key is not working.
With keyd.service stop, I can using `sudo evtest` to veryify the google assistant key shows `type 4 (EV_MSC), code 4 (MSC_SCAN), value d8`.
The file `/etc/udev/hwdb.d/61-eve-keyboard.hwdb` is present.

**Comment by ChocolateLoverRaj** [comment]
What is the key supposed to be mapped to? Super? Capslock?

**Comment by livexia** [comment]
I think esc/meta/cpaslock are all good options.

**Comment by venomade** [comment]
I got the assistant key working on a Pixelbook Go (Atlas) by following this post on deskthority to add evdev rules:
https://deskthority.net/viewtopic.php?t=24076

I stopped keyd:
`systemctl stop keyd`

Ran `evtest` to find keycodes for Assistant and Search which gave me `d8` and `db` respectively.

Copied the first part of the modalias info from the same device selected in evtest:
`cat /sys/class/input/event0/device/modalias`

Created the file `/etc/udev/hwdb.d/70-keyboard.hwdb` with the info gathered:
```
evdev:input:b0011v0001p0001eAB83*
# Add Assistant Key as Meta
 KEYBOARD_KEY_d8=key_leftmeta
# Change Search Key to Caps
 KEYBOARD_KEY_db=key_capslock
```

Ran `systemd-hwdb update ; udevadm trigger` and restarted keyd: `systemctl start keyd`

This was all done as root on Debian 12, your input device info is probably different especially on Eve so go through the linked post.

**Comment by livexia** [comment]
I cam confirm this is working on my pixelbook go with fedora. My keyboard device is `/sys/class/input/event2`.Linked post is a great read. I think someone should make a pr.

**Comment by livexia** [comment]
With more [reading](https://tech.crthaze.com/post/udev-hwdb-keyboard-remapping/) and digging. I think there is a problem with the [repo provided hwdb file](https://github.com/WeirdTreeThing/cros-keyboard-map/blob/main/configs/61-eve-keyboard.hwdb).

In the file `61-eve-keyboard.hwdb` the udev match rule is `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnGoogle:pnEve:pvr*`.

In pixelbook go, using `sudo udevadm test /sys/class/input/event2 |& grep builtin.command..hwdb | perl -pe "s/^.+'hwdb '(evdev:.+)''/- \1/" | grep '^- evdev' | grep Eve` to get the HWDB entries.

```
sudo udevadm test /sys/class/input/event2 |& grep builtin.command..hwdb | perl -pe "s/^.+'hwdb '(evdev:.+)''/- \1/" | grep '^- evdev'
- evdev:atkbd:dmi:bvncoreboot:bvrMrChromebox-2408.0:bd09/08/2024:br24.8:efr0.0:svnGoogle:pnAtlas:pvr1.0:rvnGoogle:rnAtlas:rvr1.0:cvnGoogle:ct9:cvr:sku:
- evdev:name:AT Translated Set 2 keyboard:dmi:bvncoreboot:bvrMrChromebox-2408.0:bd09/08/2024:br24.8:efr0.0:svnGoogle:pnAtlas:pvr1.0:rvnGoogle:rnAtlas:rvr1.0:cvnGoogle:ct9:cvr:sku:
- evdev:name:AT Translated Set 2 keyboard:phys:isa0060/serio0/input0:ev:120013:dmi:bvncoreboot:bvrMrChromebox-2408.0:bd09/08/2024:br24.8:efr0.0:svnGoogle:pnAtlas:pvr1.0:rvnGoogle:rnAtlas:rvr1.0:cvnGoogle:ct9:cvr:sku:
```

So the matching rule for Atlas should be `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnGoogle:pnAtlas:pvr*`.

With this hwdb file the assistant key and search key is mapped as I wanted.
```
evdev:atkbd:dmi:bvn*:bvr*:bd*:svnGoogle:pnAtlas:pvr*
 KEYBOARD_KEY_d8=leftmeta
 KEYBOARD_KEY_db=capslock
```

**Comment by venomade** [comment]
Nice Work! Replacing the product name in the matching rule with a wildcard also seems to work: `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnGoogle:pn*:pvr*`. So as long as the rule is only installed on Nocturne, Atlas and Eve as per [install.sh](https://github.com/WeirdTreeThing/cros-keyboard-map/blob/b2e69368f96bdf7562dc1a95a0d863c794756842/install.sh#L79) it should just work.
I'll create a PR.

**Comment by livexia** [comment]
Yes, maybe having three matching rules for each product name is also a viable solution.

**Comment by venomade** [comment]
I don't think anyone in this issue has a Pixel Slate (Nocturne) so if that is somehow different, then individual rules would make sense but it seems unnecessary otherwise.
