### ISSUE TITLE
Pressing search key does not shift to fn keys

### ISSUE THREAD

**Issue by abhi-deshpande** [WeirdTreeThing/cros-keyboard-map#14]
Device - Octopus Lick
OS - Fedora 39

After running the installation script, it got some trouble installing keyd, maybe because keyd is not available in default dnf repos. I installed keyd manually afterwards. (Copr)

After re-running the installation script, it installed the keymap configs correctly. Running evtest shows all the keys correctly (back, reload, brightness, volume...etc. Total 10 keys) but when I press search key combinations, no Fn keys (F1, F2....etc.) are being shown in evetst. I tried inverting the map as well, no luck.

Applications like firefox seem to completely ignore the zoom key, even when it is assigned to F11. Full-screen does not work. Although pressing "F" works.

**Comment by WeirdTreeThing** [comment]
Send the cros.conf that was generated

**Comment by abhi-deshpande** [comment]
Sure. Here it is -

```
[ids]
k:18d1:5057
k:18d1:5050
k:0000:0000
k:18d1:504c
k:18d1:503c
k:18d1:5044
k:18d1:502b
k:18d1:5061
k:18d1:503d
k:18d1:5052
k:18d1:505b
k:0001:0001
k:18d1:5030

[main]
f1 = back
f2 = forward
f3 = refresh
f4 = f11
f5 = scale
f6 = brightnessdown
f7 = brightnessup
f8 = mute
f9 = volumedown
f10 = volumeup

back = back
forward = forward
refresh = refresh
zoom = f11
scale = scale
brightnessdown = brightnessdown
brightnessup = brightnessup
mute = mute
volumedown = volumedown
volumeup = volumeup

f13=coffee
sleep=coffee

[meta]
f1 = f1
f2 = f2
f3 = f3
f4 = f4
f5 = f5
f6 = f6
f7 = f7
f8 = f8
f9 = f9
f10 = f10

back = f1
forward = f2
refresh = f3
zoom = f4
scale = f5
brightnessdown = f6
brightnessup = f7
mute = f8
volumedown = f9
volumeup = f10


[alt]
backspace = delete
brightnessdown = kbdillumdown
brightnessup = kbdillumup
f6 = kbdillumdown
f7 = kbdillumup

[control]
f5 = print
scale = print

[control+alt]
backspace = C-A-delete
```

**Comment by abhi-deshpande** [comment]
BTW, Ctrl + Alt + Backspace is also not working. Could it be some dependency issue ?

**Comment by abhi-deshpande** [comment]
@WeirdTreeThing while tracing out the problem, I found that the keyd package I installed had a problem. I migrated to another maintained copr repo and then it started working. Now everything is working.

**Comment by WeirdTreeThing** [comment]
Oh ok.
