### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by vlothedev** [WeirdTreeThing/cros-keyboard-map#17]
![image](https://github.com/WeirdTreeThing/cros-keyboard-map/assets/123765798/bbc49424-71fe-4b87-aed9-c567da9ef67c) im on void linux and the audio script worked fine

**Comment by WeirdTreeThing** [comment]
The script has been updated, try again.

**Comment by vlothedev** [comment]
I still have the bug

**Comment by WeirdTreeThing** [comment]
The error is the same even after git pulling?

**Comment by captain-baha** [comment]
I get the same error in Fedora 39 XFCE spin. Below is from my terminal.

```
mike@fedora:~/cros-keyboard-map128$ git clone https://github.com/WeirdTreeThing/cros-keyboard-map
Cloning into 'cros-keyboard-map'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 140 (delta 30), reused 36 (delta 18), pack-reused 83
Receiving objects: 100% (140/140), 42.00 KiB | 10.50 MiB/s, done.
Resolving deltas: 100% (75/75), done.
mike@fedora:~/cros-keyboard-map$ cd cros-keyboard-map
mike@fedora:~/cros-keyboard-map/cros-keyboard-map$ ./install.sh
Installing keyd dependencies
./install.sh: line 42: [: !: integer expression expected
Installing keyd
./install.sh: line 58: [: : integer expression expected
```

**Comment by WeirdTreeThing** [comment]
try now

**Comment by WeirdTreeThing** [comment]
Try now

**Comment by captain-baha** [comment]
Successful install and working. Thank you for your very quick responses and fix!

`By default, the top row keys will do their special function (brightness, volume, browser control, etc).
Holding the search key will make the top row keys act like fn keys (f1, f2, f3, etc).
Would you like to invert this? (y/N) n
Installing config
Enabling keyd
Created symlink /etc/systemd/system/multi-user.target.wants/keyd.service → /usr/local/lib/systemd/system/keyd.service.
Installing libinput configuration
Done
`
