### ISSUE TITLE
F5 broken on devices with a screenshot key

### ISSUE THREAD

**Issue by gdbaldw** [WeirdTreeThing/cros-keyboard-map#26]
The top row keys work as intended. But, the Meta Key does not change their behavior. No function keys.

How can I help debug this issue?

**Comment by gdbaldw** [comment]
Trying different key combinations, I stumbled on `<CTRL><ALT><META><top row key>` from the left gives tty1, tty2, tty3, tty4, but not tty5+. And, I can't return to the graphical display from the tty.

**Comment by WeirdTreeThing** [comment]
If you let go of every mod key, press them again, and then press f6+, will that work? I've noticed that f5 seems to not work as intended on newer devices, not yet sure why though.

**Comment by gdbaldw** [comment]
Yes! Letting go and pressing again gives me f6 and for f7, returns to graphic mode. Very good.

Can we debug the `<CTRL><ALT>` modifier needed for `<META>`?
How about f5?

It all works ok for my needs, however if we can debug further, I'm game.

**Comment by WeirdTreeThing** [comment]
I have a device affected by this, so I can debug whenever I have the time to.

**Comment by ChocolateLoverRaj** [comment]
I'm not using this script, but F5 (and other Meta+top row keys) is working perfectly on my jinlon on NixOS with keyd v2.4.3. I am not switching ttys though. That might be part of the problem.

**Comment by WeirdTreeThing** [comment]
This issue only affects devices that have a screenshot key where the default behavior is to act like the printscreen (sysrq) key. I have no clue if that's how jinlon behaves. I suspect the issue is related to sysrq being treated special by linux and/or keyd.

**Comment by WeirdTreeThing** [comment]
This also makes me realize that jinlon is probably another edge case device where I can't detect the layout.

**Comment by ChocolateLoverRaj** [comment]
Oh yeah I started having a problem with the screenshot key being "sysreq". I [updated my keyd config](https://github.com/ChocolateLoverRaj/nixos-system-config/commit/f6295cefb5a1eca27309ade92208aee9f14b8314) so that Super+Screenshot does F5. I didn't have to include it in `main` since "sysreq" takes a screenshot OOTB anyways.

**Comment by WeirdTreeThing** [comment]
Sure enough, replacing `print` with `sysrq` fixes this issue.
