### ISSUE TITLE
EVE 'Assistant' key not functional

### ISSUE THREAD

**Issue by Baeldaeg** [WeirdTreeThing/cros-keyboard-map#40]
The 'Assistant' key on EVE doesn't do anything. Running Debian.

I can make it temporarily work as the meta key with `setkeycodes 0xd8 125` but I'm not sure that's the right way to do it.

**Comment by WeirdTreeThing** [comment]
The script installs a udev rule to map the assistant key to super, maybe that isn't being applied?

**Comment by Baeldaeg** [comment]
I ran 
`sudo udevadm hwdb --update`
and
`sudo udevadm trigger`
And now it works.

**Comment by WeirdTreeThing** [comment]
I can add that to the script
