### ISSUE TITLE
Fedora 41 kde plasma overview button

### ISSUE THREAD

**Issue by Lucaacer** [WeirdTreeThing/cros-keyboard-map#42]
Just a question, in my configuration the overview / f5 button does not work because it should be remapped to org.kde.kglobalaccel /component/kwin invokeShortcut Overview that is the current command to invoke the overview mode in kde plasma. I have tried to modify the config of your file (which is ok for all the other keys) in any way I could figure but I  have so far been unable to get it working,

May I ask you any suggestion?

Thanks in advance.

**Comment by WeirdTreeThing** [comment]
In plasma 5, the overview button was mapped by default. That mapping was removed in plasma 6 though. You can manually add it back.

**Comment by Lucaacer** [comment]
Found, thanks. It was quite hidden in plasma settings.
