### ISSUE TITLE
keyd Service is not automatically started when in Chimera Linux

### ISSUE THREAD

**Issue by Catbirby** [WeirdTreeThing/cros-keyboard-map#6]
On Chimera, the script attempts to start the service using the OpenRC commands instead of using dinit.

**Comment by WeirdTreeThing** [comment]
I don't think upstream supports dinit, see if you can get this packaged in Chimera.

**Comment by WeirdTreeThing** [comment]
Fixed in [25b0e9c](https://github.com/WeirdTreeThing/cros-keyboard-map/commit/25b0e9c2a10fc834d414b427c40d572fb38cda14)
