### ISSUE TITLE
How to map context menu (right click) to lock key?

### ISSUE THREAD

**Issue by DoughMucker** [WeirdTreeThing/cros-keyboard-map#7]
This tool is awesome. It remaps those keys nicely. I'd like to modify the lock key to a context menu key as Super+L can be used to lock the device. I can't quite figure it out. I've modified cros-keyboard-map.py to so many variations of "context menu" as shown but haven't got it to work. The change reverts the lock key to launch Settings.

 #map lock button to coffee
 #ORIG#config += "\nf13=coffee\nsleep=coffee\n"
config += "\nsleep=coffee\n"
config += "\nf13=kbdcontextmenu\n"

Thanks for any help.
Doug

Edit:
I found that Shift+F10 (or Shift+Super+VolumeUp with your mapping) works.

**Comment by WeirdTreeThing** [comment]
So is the issue solved?

**Comment by DoughMucker** [comment]
Yes, I suppose. It'll take some getting used to, but will work. Was hoping for just that one key to work. I was able to remap that key to pretty much anything else (trying to isolate the issue) just not context menu. Similarly, I was trying to use this to remap Control+Down to pgdn (next) and Control+Up to pgup (prior) but couldn't. Oh well. Thanks again for your scripts!
