### ISSUE TITLE
Executing the script turns touchscreen gesture to "--"

### ISSUE THREAD

**Issue by etieng** [WeirdTreeThing/cros-keyboard-map#8]
Hi !

**Setup**
Akali360
KDE Néon 5.27
Kernel 6.5.0-15-generic x64
X11
MrChromebox firmware 4.22.2 UEFI

**What**
After running `cros-keyboard-map`
Touchscreen is not a touchscreen anymore, it's a "-" key.

Did I mess with something ? What log should I provide ? Anyone can help me get the touchscreen back ?

**Comment by etieng** [comment]
```
~$ sudo keyd

CONFIG: parsing /etc/keyd/cros.conf
Starting keyd v2.4.3 (dcbb68b)
DEVICE: ignoring 0fac:1ade  (keyd virtual pointer)
DEVICE: ignoring 04f3:00bb  (Elan Touchpad)
DEVICE: ignoring 2d1f:0066  (WCOM005C:00 2D1F:0066)
DEVICE: ignoring 2d1f:0066  (WCOM005C:00 2D1F:0066 Stylus)
DEVICE: match    0000:0000  /etc/keyd/cros.conf (Elan Touchscreen)
DEVICE: match    0001:0001  /etc/keyd/cros.conf (AT Translated Set 2 keyboard)
```

Thanks for pointing me in that direction.
I commented the Elan Touchscreen in the file `/etc/keyd/cros.conf` and then it works as it does.
```
[ids]
0001:0001
#0000:0000

```

**Comment by WeirdTreeThing** [comment]
Thanks, I pushed a fix to the script. Try it and see if it works properly now.

**Comment by etieng** [comment]
I ran the script again after after pulling from git.
The result in `/etc/keyd/cros.conf` is this :
```
[ids]
k:0001:0001
k:0000:0000
```
And `keyd` now ignore Elan Touchscreen
```
$ sudo keyd
CONFIG: parsing /etc/keyd/cros.conf
Starting keyd v2.4.3 (dcbb68b)
DEVICE: ignoring 0fac:1ade  (keyd virtual pointer)
DEVICE: ignoring 04f3:00bb  (Elan Touchpad)
DEVICE: ignoring 2d1f:0066  (WCOM005C:00 2D1F:0066)
DEVICE: ignoring 2d1f:0066  (WCOM005C:00 2D1F:0066 Stylus)
DEVICE: ignoring 0000:0000  (Elan Touchscreen)
DEVICE: match    0001:0001  /etc/keyd/cros.conf (AT Translated Set 2 keyboard)
```

**Comment by WeirdTreeThing** [comment]
Perfect!
